<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Statistics Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 20px;
            padding: 0;
            color: #333;
            font-size: 12px;
        }
        h1 {
            text-align: center;
            color: #222;
            margin-bottom: 5px;
        }
        h3 {
            text-align: center;
            color: #555;
            margin-top: 0;
        }
        .section-title {
            font-weight: bold;
            margin-top: 20px;
            font-size: 14px;
            color: #222;
            border-bottom: 1px solid #ccc;
            padding-bottom: 4px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }
        table th, table td {
            border: 1px solid #ccc;
            padding: 6px 8px;
            text-align: center;
        }
        table th {
            background-color: #f8f8f8;
            font-weight: bold;
        }
        .summary-box {
            margin-top: 15px;
            padding: 8px;
            border: 1px solid #ccc;
            background-color: #f8f8f8;
            width: 100%;
        }
        .summary-box p {
            margin: 5px 0;
            font-size: 12px;
        }
        .footer {
            text-align: center;
            font-size: 11px;
            margin-top: 15px;
            color: #888;
        }
    </style>
</head>
<body>
    <h1>TenaMart Waiting List Statistics</h1>
    <h3>Generated on {{ now()->format('F j, Y') }}</h3>

    {{-- Summary Stats --}}
    <div class="summary-box">
        <p><strong>Total Signups:</strong> {{ $stats['stats']['total'] ?? 0 }}</p>
        <p><strong>Signups Today:</strong> {{ $stats['stats']['today'] ?? 0 }}</p>
        <p><strong>Top Signup Source:</strong> 
            {{ $stats['stats']['top_source']['signup_source'] ?? 'N/A' }} 
            ({{ $stats['stats']['top_source']['total'] ?? 0 }})
        </p>
    </div>

    {{-- Top Sources Table --}}
    <div class="section-title">Top Signup Sources</div>
    <table>
        <thead>
            <tr>
                <th>Source</th>
                <th>Total Signups</th>
            </tr>
        </thead>
        <tbody>
            @forelse($stats['top_sources'] ?? [] as $source)
                <tr>
                    <td>{{ $source['signup_source'] ?? 'Unknown' }}</td>
                    <td>{{ $source['total'] ?? 0 }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="2">No data available</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{-- Trend Table --}}
    <div class="section-title">Signups Trend</div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Signups</th>
            </tr>
        </thead>
        <tbody>
            @forelse($stats['trend'] ?? [] as $trend)
                <tr>
                    <td>{{ $trend['date'] ?? 'N/A' }}</td>
                    <td>{{ $trend['count'] ?? 0 }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="2">No trend data available</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by TenaMart Dashboard • {{ now()->format('Y') }}
    </div>
</body>
</html>
